### ISSUE TITLE
migrate gips from gippy==0.3.* to gippy==1.0.0

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#376]
(Note that effort was made in 2017 that was then largely abandoned; the work restarts in circa 2019; see below.)

**Comment by ags-tolson** [comment]
The official changelog says gippy 1.0 is substantially backward-incompatible, and that `DataType` replaces, I think, `GDT_` types; few other details or other gippy docs seem relevant.  It also suggests that reading `diff gippy-0.3.ours gippy-1.0` would be prohibitive.

Just to get going, I'll start with an A/B system test run, starting with modis, and just see what breaks with new gippy installed.  I think I can annotate the gippy calls with a code coverage tool, so we'll know what's been tested and what hasn't.

**Comment by ags-tolson** [comment]
So I can't get a coverage report for a subprocess, which precludes the direct use of the system tests for the purpose.  After faffing about trying to make it work, I gave up and am doing a two-step workaround, something like:

```
(.venv) $ pytest --sys -k 'modis and process and sys' $OTHER_OPTIONS_HERE
(.venv) $ time coverage run `which gips_process` \
> modis -s /home/tolson/src/also-gips/gips/test/NHseacoast.shp -d 2012-12-01,2012-12-03 -v 4
```

This way I can run the test, prove it passes, then get coverage info to prove certain gippy calls are being finished successfully.

**Comment by ircwaves** [comment]
can't you use the `pytest-coverage` module and add a `--cov` to your pytest invocation?

**Comment by ags-tolson** [comment]
That's what I tried, with pytest-cov (pytest-coverage seems to be a stale name for pytest-cover, which is a stale fork of pytest-cov).  It installed, then I ran it and got a coverage report, eg:

```
(.venv) $ time pytest --ll debug -s -x -vv --sys -k 'modis and sys and t_process' --cov-report annotate --cov
```

But the coverage data doesn't seem to include the subprocesses, so it'd look like the system test code was called, but that eg `modisData.process` wasn't.  I have this memory that it used to work, though, just as you suggest.

The good news is that unit & integration tests, which don't usually run subprocesses, ought to work, and given many of the breakages seem to be compile-time problems such as ImportError and NameError, that part of the test suite may be a better place to start anyway.  My bad for not thinking of it sooner.  : /

**Comment by ircwaves** [comment]
--
/*
 * Ian Cooke
 * Applied GeoSolutions
 * 87 Packers Falls Road
 * Durham, NH 03824 USA
 * www.appliedgeosolutions.com
 * icooke@ags.io
 * 603.292.1194
 */

**Comment by ircwaves** [comment]
weird...pytest-cov==2.5.1 (current) says:
> ... It also supports coverage of subprocesses.

**Comment by ags-tolson** [comment]
Unit and integration tests pass with gippy 1.0 in the branch 376-gippy-update:

https://github.com/Applied-GeoSolutions/gips/commit/7a829c337c43b89d343371c91b1e7d1fab684cf0

I have yet to complete the B side of the A/B test, because most of the problems are renamings of methods and functions, which means it just crashes on the first AttributeError, so the error reports and coverage measurements are both pretty nearly useless.  It's hard to estimate because each AttributeError is like a wall that you can only see past if you fix it.

So, I'm going to spend today fixing the modis process test, and time permitting, the other modis system tests.  Then we'll have a sense of how much pain goes in fixing a certain volume of driver code, then we can roughly estimate the remainder.  It's also a head start on the work itself.

**Comment by ags-tolson** [comment]
9310f6f has product generation for modis with gippy 1.0.

The a/b test is showing very similar rasters for all the products.  Two exceptions are obstime and temp, which mostly show no-data.  I think there are plans to get a science eyeball or two on the two sets of product files.

**Comment by ags-tolson** [comment]
Pivoting to the export/project part of the codebase; command-lines I'll be working with:

```
gips_project modis -s /home/tolson/src/also-gips/gips/test/NHseacoast.shp -d 2012-12-01,2012-12-03 -v 4 --res 100 100 --outdir /home/tolson/src/also-gips/output --notld
gips_project modis -s /home/tolson/src/also-gips/gips/test/NHseacoast.shp -d 2012-12-01,2012-12-03 -v 4 --outdir /home/tolson/src/also-gips/output --notld
gips_tiles modis -s /home/tolson/src/also-gips/gips/test/NHseacoast.shp -d 2012-12-01,2012-12-03 -v 4 --outdir /home/tolson/src/also-gips/output --notld
gips_tiles modis -t h12v04 -d 2012-12-01,2012-12-03 -v 4 --outdir /home/tolson/src/also-gips/output --notld
```

**Comment by ags-tolson** [comment]
Update on landsat:  Shortly I'll push commits that update the landsat driver to gippy 1.0.  Lots of processing has been verified, however no atmo correction has been checked as it looks like we can get away with just eyeballing it.

Several products are broken or have been skipped for various reasons.  Here's a list; if it's not here, then the product has been checked and visually matched against output from the dev branch:

```
differences in product - visually shown in qgis and in gdalinfo -stats
    ndti    values seem inverted
    satvi   darker
    sti     values seem inverted

broken/skipping/both
    tcap    segfaults, prevented with NotImplementedError
    wtemp   AttributeError: type object 'merraData' has no attribute 'profile'
    ndvi8sr  SR not super relevant
    landmask SR not super relevant
    all ACOLITE (acoflags fai oc2chl oc3chl rhow spm655 turbidity)
        reason not remembered atm
    acca    superceded by cloudmask (also errors out)
    fmask   superceded by cloudmask (also error, missing band 'water'
    bqa     NameError
    bqashadow missing ags-gippy's AddShadowMask
```

**Comment by ags-tolson** [comment]
gips_project, gips_tiles, and landsat conversion to gippy 1.0:

https://github.com/Applied-GeoSolutions/gips/compare/9310f6f23c75b1e7c41927768cbe7c60037fc488...9d0062b5f3b10b2d4c8a473c5d6db76ee8352de8

**Comment by ags-tolson** [comment]
Overall progress for the gippy 1.0 effort:

```
# done infrastructure
gips/data/core.py:import gippy
gips/parsers.py:import gippy
gips/tiles.py:import gippy
gips/tiles.py:from gippy import algorithms
gips/inventory/__init__.py:import gippy
gips/utils.py:import gippy
gips/utils.py:from gippy import GeoVector

# done drivers
gips/data/modis/modis.py:import gippy
gips/data/modis/modis.py:from gippy import algorithms
gips/data/landsat/landsat.py:import gippy
gips/data/landsat/landsat.py:from gippy import algorithms

# todo drivers
gips/data/prism/prism.py:from gippy import GeoImage
gips/data/sar/sar.py:import gippy
gips/data/sarannual/sarannual.py:import gippy
gips/data/merra/merra.py:import gippy
gips/data/sentinel2/sentinel2.py:import gippy
gips/data/sentinel2/sentinel2.py:import gippy.algorithms
gips/data/daymet/daymet.py:import gippy
gips/data/weld/weld.py:import gippy
gips/data/aod/aod.py:import gippy

# todo infrastructure
gips/scripts/mask.py:import gippy - triaged/prepped
may be useful to run gips_stats just to check
```

**Comment by ags-tolson** [comment]
I pushed a round of fixes, mostly to sentinel-2 and a bit of wrap-up as a transition to other work.  Right now the the last remaining effort is:

- [ ] Convert the remaining drivers
- [ ] Do something about SetColorTable (see gippy issue mentioned above)
- [ ] Get the OK from the science team (give them the results of before-and-after product generation)
- [ ] Update the system tests & confirm the unit tests still pass

**Comment by ags-tolson** [comment]
Drivers with significant differences in their products:

landsat and sentinel2, these look visually different:
*    ndti
*    satvi
*    sti
*    cloudmask (for landsat)
*    bi (for sentinel2)

Weld has an issue with its NDVI; the gdalinfo stats are slightly different (less than 1%) and visually it looks a little different.

**Comment by ags-tolson** [comment]
Submitting a PR shortly.  Color tables aren't supported in gippy 1.0, and neither is AddShadowMask nor alltouch, so products that depend on those either have that feature turned off, or the product turned off entirely via exception.  The /scratch dir has updated a/b product generations for science team examination.

**Comment by ags-tolson** [comment]
Submitting a PR shortly.  Color tables aren't supported in gippy 1.0, and neither is AddShadowMask nor alltouch, so products that depend on those either have that feature turned off, or the product turned off entirely via exception.  The /scratch dir has updated a/b product generations for science team examination.

**Comment by ircwaves** [comment]
- [ ] create migration README doc (incl. missing functionality list, and mapping of common v0.3.x calls to v1.0.x calls)
- [ ] use this list as a guide to scope gips-bin update effort

**Comment by ags-tolson** [comment]
Conversion guide for gippy 1.0:

https://gist.github.com/ags-tolson/8884c323f49d07eecbf243a299c0b88c

**Comment by ags-tolson** [comment]
I left a summary of gippy 1.0 conversion information in new gips-bin issue, number 73.

**Comment by ags-tolson** [comment]
Updated the conversion guide to note issues with `GeoImage().read()` and `algorithms.acca`:

https://gist.github.com/ags-tolson/8884c323f49d07eecbf243a299c0b88c

**Comment by ircwaves** [comment]
I think this difference falls under consequences-of-gippy-being fixed:
```
             -    '  AOD Source=MODIS (MOD08_D3)',
E             +    '  AOD Source=MODIS (MOD08_D3) spatial average',
E             ?                                  ++++++++++++++++
E             -    '  AOD Value=0.066',
E             ?                    ^^
E             +    '  AOD Value=0.05450000',
E             ?                    ^^^^^^^
```

I'll investigate this a bit and report back.

**Comment by bhbraswell** [comment]
I agree that is a large enough difference to warrant a closer look.

**Comment by ra-tolson** [comment]
hls msavi2's standard deviation seems to have drifted; is that big enough to warrant investigation?  Note visual inspection looked okay.  Diff:
```
                -    '  Minimum=0.000, Maximum=10160.000, Mean=2014.882, StdDev=590.982',
                +    '  Minimum=0.000, Maximum=10160.000, Mean=1972.869, StdDev=651.815',
```

**Comment by ircwaves** [comment]
Still work to be done w.r.t. gippy, but this has merged to `dev`.
